### ISSUE TITLE
extract_json 函数报错

### ISSUE THREAD

**Issue by Luooke6002** [vicety/pixiv-beta#5]
你好， 我昨天下载了你的Pixiv-Crawler，在运行main.py的过程中报错。
        start = text.find(query_text) + len(query_text)
上面这行代码不起作用，我看了一下图片网页源码，发现：
illust:{ 
69758991(pid)：**{
{要提取的内容}
}**
}
要提取的内容（上面加粗部分）在text(response.body)中没有找到。
作者君，有啥解决方法么？
![image](https://user-images.githubusercontent.com/41477211/43003288-92f97754-8c5e-11e8-95a8-ebe49ba8cf8c.png)
![image](https://user-images.githubusercontent.com/41477211/43003311-bfd6a148-8c5e-11e8-8edb-02d4f527f5f6.png)

**Comment by vicety** [comment]
我也不太确定为什么会出现这样的问题，我看了一下返回的response.body，在html head 第九个script下是有这个json的
![image](https://user-images.githubusercontent.com/22413370/43032166-61641c82-8ce3-11e8-9b1f-f0d33a0947e8.png)
你发的第一张图应该就是要提取出来的json内容，如果pixiv-beta.py 326行的text就是第一张图的内容的话，那应该是没有问题的

**Comment by Luooke6002** [comment]
感谢作者君，找到问题了，是我密码输入错了。 
非常感谢作者君的分享，阿里嘎多。
